apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: order
spec:
  containers:
  - name: order
    image: fyerfyer/order:1.0.0
    env: 
      - name: APPLICATION_PORT
        value: "8082"
      - name: REDIS_ADDR
        value: "redis:6379"
      - name: DATA_SOURCE_URL
        value: "root:pa55word@tcp(mysql:3306)/orders"
      - name: PAYMENT_SERVICE_ADDR
        value: "payment:8081"
      